name: formgen
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  validators: ^3.0.0
  meta: 

dev_dependencies:
  test:
  lint: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec